### ISSUE TITLE
Fetch Video URL error. Download error.

### ISSUE THREAD

**Issue by bozzmob** [gekowa/node-pd#19]
I am not sure why there are errors coming up all of a sudden.
Lot of video modules downloaded, then, I am encountering this issue.

|--Clip: Duck Tails: Modules Are Singletons
Already finished.
|--Clip: Summary
Already finished.
Module: Beyond Basic Functions
**|--Clip: Function Review
Fetch Video URL error.
Download error.
|--Clip: Callable Instances
Fetch Video URL error.
Download error.
|--Clip: Classes Are Callable
Fetch Video URL error.
Download error.
|--Clip: Conditional Expressions**

Please suggest a fix or let me know how I can contribute to the same.

**Comment by gekowa** [comment]
I've seen this issue before, did you run the source code with node or use the published npm package?

**Comment by bozzmob** [comment]
@gekowa Yes, 'maybe' that's the issue. My subscription is not plus.

But, one thing to note is initial few modules(videos clips) downloaded, and then suddenly I encountered this.

**Comment by bozzmob** [comment]
@gekowa I tried what you suggested - `npm install -g node-pd@0.0.15`
and then tried downloading-

|--Clip: Summary
Already finished.
**Module: Beyond Basic Functions
|--Clip: Function Review
Fetch Video URL error.
Download error.
|--Clip: Callable Instances
Fetch Video URL error.
Download error.
|--Clip: Classes Are Callable
Fetch Video URL error.
Download error.
|--Clip: Conditional Expressions
Fetch Video URL error.
Download error.
|--Clip: Lambdas**


Still facing the same issue.

**Comment by gekowa** [comment]
Please first check if your account is locked out, just login from pluralsight.com and try to open a video.

**Comment by bozzmob** [comment]
@gekowa It was locked for high-activity. But, later they released it or activated it again once I replied to their email.

It works fine on the browser, take a look at it-

<img width="1421" alt="screen shot 2016-12-07 at 9 58 42 am" src="https://cloud.githubusercontent.com/assets/1252941/20954733/e15addd8-bc63-11e6-84fb-393453693e5a.png">

**Comment by bozzmob** [comment]
**An update:**

I went ahead and deleted the existing course. Tried another course in python.
I kind of see a pattern in the downloads-

```

success!
Downloading: 1 of 1 course(s).
Loading course: [python-fundamentals]
Course: Python Fundamentals 
Module: Introduction to the Python Fundamentals course
|--Clip: Introduction
Done.
|--Clip: Python Promo
Done.
|--Clip: Course Structure
Done.
|--Clip: Python Overview, Part 1
Done.
|--Clip: Python Overview, Part 2
Done.
Module: Getting Starting With Python 3
|--Clip: Introduction
Fetch Video URL error.
Download error.
|--Clip: Installing Python 3 on Windows
Fetch Video URL error.
Download error.
|--Clip: Installing Python 3 on Linux
Fetch Video URL error.
Download error.
|--Clip: Installing Python 3 on Mac OS X
Fetch Video URL error.
Download error.
|--Clip: The Read-Eval-Print-Loop or REPL
Fetch Video URL error.
Download error.
|--Clip: Significant Whitespace in Python
Fetch Video URL error.
Download error.
|--Clip: Python Culture and the Zen of Python
Fetch Video URL error.
Download error.
|--Clip: Importing From the Python Standard Library
Fetch Video URL error.
Download error.
|--Clip: Scalar Types: int, float, None and bool
Fetch Video URL error.
Download error.
|--Clip: Relational Operators
Fetch Video URL error.
Download error.
|--Clip: Conditional Statements
Fetch Video URL error.
Download error.
|--Clip: While Loops
Fetch Video URL error.
Download error.
|--Clip: Summary
Fetch Video URL error.
Download error.
Module: Strings and Collections
|--Clip: Introduction
Done.
|--Clip: Strings
Done.
|--Clip: Moment of Zen: Practicality Beats Purity
Done.
|--Clip: Strings (Continued)
Done.
|--Clip: Bytes
Done.
|--Clip: Lists
Done.
|--Clip: Dictionaries
Done.
|--Clip: For-Loops
Done.
|--Clip: Putting it All Together
Done.
|--Clip: Summary
Done.
Module: Modularity
|--Clip: Introduction
Fetch Video URL error.
Download error.
|--Clip: Creating, Running, and Importing a Module
Fetch Video URL error.
Download error.
|--Clip: Defining Functions and Returning Values
Fetch Video URL error.
Download error.
|--Clip: Distinguishing Between Module Import and Module Execution
Fetch Video URL error.
Download error.
|--Clip: The Python Execution Model
Fetch Video URL error.
Download error.
|--Clip: Main Functions and Command Line Arguments
Fetch Video URL error.
Download error.
|--Clip: Sparse Is Better Than Dense
Fetch Video URL error.
Download error.
|--Clip: Documenting Your Code Using Docstrings
Fetch Video URL error.
Download error.
|--Clip: Documenting Your Code With Comments
Fetch Video URL error.
Download error.
|--Clip: The Whole Shebang
Fetch Video URL error.
Download error.
|--Clip: Summary
Fetch Video URL error.
Download error.
Module: Objects
|--Clip: Introduction
Done.
|--Clip: Argument Passing
Done.
|--Clip: Function Arguments in Detail
Done.
|--Clip: Python's Type System
Done.
|--Clip: Variable Scoping
Done.
|--Clip: Moment of Zen
Done.
Waiting 13s

```


Every **EVEN(2,4,6...) module is failing**. And every **ODD(1,3,5...) module is downloading fine**.
I tried to download the whole course and this is how its behaving.

**Comment by gekowa** [comment]
Thanks for the update, I'll try to download the same course and see what happens to me.

**Comment by bozzmob** [comment]
I can confirm that the issue is with this ODD-EVEN thing. I tried it for
few courses, all of them failed this way.

**Comment by bozzmob** [comment]
Yes, please do check by downloading the same.

**Comment by bozzmob** [comment]
I can confirm that the issue is with this ODD-EVEN thing. I tried it for few courses, all of them failed this way.
Yes, please do check by downloading the same.

**Comment by gekowa** [comment]
I tried the same course and didn't recreate your issue. By the way, I updated a new version, which can display your subscription type and utilize "offline" API accordingly. Please update and see what happens. Thank you for helping me testing the issue

**Comment by bozzmob** [comment]
This looks like its fixed. Thanks 👍
