### ISSUE TITLE
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

### ISSUE THREAD

**Issue by bozzmob** [gekowa/node-pd#20]
If possible or needed, we can plan to change to code to use uuid module.
Just posted so that it can be tracked.

`npm WARN deprecated node-uuid@1.4.7: use uuid module instead`

Observed this in **node-pd@0.0.15**

**Comment by gekowa** [comment]
Yes, this has been fixed in the latest release.

**Comment by bozzmob** [comment]
Ok. Will close the issue 👍

**Comment by Dhaneshmonds** [comment]
I am getting the same error.

Here is my package.json
{
  "name": "angular2-demo",
  "version": "1.0.0",
  "scripts": {
    "start": "concurrent \"npm run tsc:w\" \"npm run lite\" ",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "typings": "typings",
    "postinstall": "typings install"
  },
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-beta.7",
    "systemjs": "0.19.22",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.5.15"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.1.0",
    "typescript": "^1.7.5",
    "typings":"^0.6.8"
  }
}

Could you please guide me to correct the same.

Thanks in Advance
Dhanesh
