### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by bozzmob** [gekowa/node-pd#22]
After the new update I am getting the following error on v0.0.19

bozzmob:new satjagan$ pd config -u ssss@gmail.com -p 1234 -s /Users/bozzmob/collection/work/Tuts/python/new/
env: node\r: No such file or directory

bozzmob:new satjagan$ pd download -u ssss@gmail.com -p 1234 -s /Users/bozzmob/collection/work/Tuts/python/new/ python-fundamentals
env: node\r: No such file or directory

Its because of the line-endings. I'll fix it.

**Comment by bozzmob** [comment]
A quick fix to this would be-
Go to `lib/node_modules `folder and run the command-

`find . -type f -print0 | xargs -0 dos2unix`

**Comment by gekowa** [comment]
Thanks, in addition to merge your changes to bin/pd, I also added a build process to fix line ending each time we publish the package.
