### ISSUE TITLE
DOS format error on Linux

### ISSUE THREAD

**Issue by junwatu** [gekowa/node-pd#4]
I have error message when run `pd` command on Linux

```
/usr/bin/env: ‘node\r’: No such file or directory
```

i'm sure this is caused by some of the files that is still in DOS format. I'm able to fix this manually with `dos2unix` tool though.

**Comment by gekowa** [comment]
Please go ahead and fix, thank you!

I'll also take some time and make the code work on Linux and Mac.

**Comment by gekowa** [comment]
Fixed in 0.0.14.
